car_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cars/', include('cars.urls')),
]

cars/urls.py
from django.urls import path
from . import views

app_name = 'cars'

urlpatterns = [
    path('list/', views.lst, name='list'),
    path('add/', views.add, name='add'),
    path('delete/', views.delete, name='delete')
]

cars/models.py
from django.db import models


# Create your models here.
class Car(models.Model):
    brand = models.CharField(max_length=20)
    year = models.IntegerField()

    def __str__(self):
        return f'Car is {self.brand} {self.year}'

cars/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from . import models


# Create your views here.
def lst(req):
    all_cars = models.Car.objects.all()
    context = {'all_cars': all_cars}
    return render(req, 'cars/list.html', context)


def add(request):
    if request.POST:
        brand = request.POST['brand']
        year = int(request.POST['year'])
        models.Car.objects.create(brand=brand, year=year)
        return redirect(reverse('cars:list'))
    else:
        return render(request, 'cars/add.html')


def delete(req):
    if req.POST:
        car_id = req.POST['pk']
        try:
            models.Car.objects.get(pk=car_id).delete()
            return redirect(reverse('cars:list'))
        except:
            return redirect(reverse('cars:list'))

    return render(req, 'cars/delete.html')

cars/templates/cars/add.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-3">
        <h1>Add</h1>
        <h5>Add New Car In The List</h5>
        <form action="" method="POST">
            {% csrf_token %}
            <div class="form-floating mb-3">
                <input type="text" class="form-control" id="brand" name="brand" placeholder="BMW">
                <label for="brand">Brand</label>
            </div>
            <div class="form-floating">
                <input type="text" class="form-control" id="year" name="year" placeholder="2010">
                <label for="year">Year</label>
            </div>
            <input class="btn btn-primary mt-3" type="submit" value="Submit">
        </form>
    </div>
{% endblock %}

cars/templates/cars/delete.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-3">
        <h1>Delete</h1>
        <form action="" method="POST">
            {% csrf_token %}
            <div class="form-floating mb-3">
                <input type="number" class="form-control" id="pk" name="pk" placeholder="Car ID">
                <label for="pk">ID</label>
            </div>
            <input class="btn btn-primary mt-3" type="submit" value="Submit">
        </form>
    </div>
{% endblock %}

cars/templates/cars/list.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-3">
        <h1>List</h1>
        <ul>
            {% for car in all_cars %}
                <li>{{ car }} | ID: {{ car.id }}</li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Car Site</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
            crossorigin="anonymous"></script>
</head>
<body>
<!-- NAV -->
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Car Site</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'cars:list' %}">List</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'cars:add' %}">Add</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'cars:delete' %}">Delete</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<!-- NAV -->
{% block content %}
{% endblock %}
</body>
</html>